version: "2"
services:
  manasa6900/app_repo:latest:
    image: app
    restart: on-failure
    depends_on:
      - db
    ports:
      - 8501:8501

    
  db:
    image: manasa6900/stock_proj:1
    
